import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import InputTimer from "../public/components/InputTime";

const Home: NextPage = () => {
  const [timerFinished, setTimerFinished] = useState(true);
  return (
    <div className={styles.container}>
      <Head>
        <title>HüberBreak</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>MicroBreak</h1>
      <p>Your customisable timer for learning. or some shit</p>
      <img
        className="asmon"
        src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.ytimg.com%2Fvi%2FVipDXeuZWok%2Fmaxresdefault.jpg&f=1&nofb=1&ipt=29006df4feffe72285223d8a6a0ea0adfbf2a3009a9a9d709ba79f2884ca2f59&ipo=images"
      ></img>
      <InputTimer />
    </div>
  );
};

export default Home;
